### ISSUE TITLE
Skapa och designa välkomstsegmentet (delen ovanför todo-listan). Segmentet skall minst innehålla tid, veckodag och datum.

### ISSUE THREAD

**Issue by Erik-wiklund** [Erik-wiklund/Todocalendar#6]

**Comment by ViktorNy** [comment]
Att göra: 

- [x] Arrangera om, så att funktioner har datum som inparameter istället för att skapa datum i varje funktion
- [x] Fixa design av elementet
- [x] Lägga till datum och tid

**Comment by ViktorNy** [comment]
Att göra: 

- [x] Visa datum + månad
